### ISSUE TITLE
camera parameters

### ISSUE THREAD

**Issue by elliestath** [MarcWong/UDD#2]
Hey, cool dataset! Are the camera parameters available? I noticed that the aerial images (not the ones from DJI) have no exif metadata, but I would be interested in knowing the focal length and some pixel size/sensor size in mm if possible. Thanks!

**Comment by MarcWong** [comment]
Now the PKU-M1 Dataset with EXIF info is on air, check this out https://drive.google.com/drive/folders/1x172jM6iF6SZjMB4jH8FVRgiuGcJDtIe
