### ISSUE TITLE
question!

### ISSUE THREAD

**Issue by zhujiesuper** [MarcWong/UDD#3]
your job is awesome ,but can you tell me the mean of m1-train200-val40-test48?   it is a new dataset?

**Comment by MarcWong** [comment]
This is just the subdivision of M1 with ground truths. And there is a little overlap between UDDs and M1. If you are training this task, just use UDD5 or UDD6 would be enough. Actually the m1-train200-val40-test48 is discarded somehow, no need to maintain the ground truth of it.

**Comment by zhujiesuper** [comment]
thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MarcWong"<notifications@github.com&gt;; 
发送时间: 2020年9月5日(星期六) 晚上9:53
收件人: "MarcWong/UDD"<UDD@noreply.github.com&gt;; 
抄送: "朱一大爱"<653725215@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [MarcWong/UDD] question! (#3)





 
This is just the subdivision of M1 with ground truths. And there is a little overlap between UDDs and M1. If you are training this task, just use UDD5 or UDD6 would be enough. Actually the m1-train200-val40-test48 is discarded somehow, no need to maintain the ground truth of it.
