### ISSUE TITLE
Can't download dataset in china .

### ISSUE THREAD

**Issue by myknowntime** [MarcWong/UDD#4]
Hi, I 'm a Chinese student, due to the Internet issues, I can't download your data from Google Drive. So, could you provide a Baidu kind link? Thank you for your kind contribution and await your reply.

**Comment by MarcWong** [comment]
@QT-Zhu Can you upload the dataset to a permeant Baidu Cloud link?

**Comment by QT-Zhu** [comment]
Try this link: https://pan.baidu.com/s/1sQavCwH29PUwTEgF3teMBQ  PW: 7qua
It contains both UDD5 and UDD6 datasets and I use P mode of PIL to store labelled GT so it can be viewed in color but directly loaded as label maps.
