### ISSUE TITLE
Configuration of ENet and DeepLab

### ISSUE THREAD

**Issue by HRHLALALA** [MarcWong/UDD#6]
Hello, thanks for the excellent work! I am trying to train and test these datasets on ENet and DeepLab but I am unable to produce such high results indicated in the benchmark section. Can you provide the detailed configurations of them? Any help will be appreciated!

**Comment by QT-Zhu** [comment]
I run tests on implementations in [this repo](https://github.com/QT-Zhu/AerialSeg). I think there is nothing special, even some results are not the best. You can check `scripts/train_UDD5.sh` or `scripts/train_UDD6.sh` for configurations.
