### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by StuLiu** [MarcWong/UDD#8]
您好！非常感谢您的工作！我有一个关于基准测试的问题，请问一下下面的结果是在验证集上计算得到的吗？还是说需要将测试集提交到测试服务器？
![image](https://user-images.githubusercontent.com/19245323/176144093-582290b5-0f8f-4c7e-82dd-51b2cb6d6535.png)

**Comment by MarcWong** [comment]
on the validation set. Currently we don't provide a test server :-)

**Comment by StuLiu** [comment]
thanks for your reply!
